""""""""""""""
" VIM Config "
""""""""""""""
set hidden								" Opening a new file causes files to be hidden instead of closed.
set nocompatible 						" Disable vi support.
set tabstop=4 shiftwidth=0				" Set gab to be 4, shifting to be as tabs.
set list listchars=tab:»·,trail:·       " Display tabs.
set undofile              				" Enable persistent undo.
set hlsearch incsearch      			" Enable incremental search and highlight as we go.
set ignorecase smartcase 				" Search should be case insensitive unless containing uppercase characters.
set relativenumber number   			" Enable line numbers relative to the cursor.
set ruler 								" Show line and character number in lower right hand corner.
set history=10000 						" Increase history for search and command line entries.
set cursorline cursorcolumn 			" Highlight the active line and the active column.
set textwidth=80 colorcolumn=81 		" Set the text width to 80 and create a vertical bar in 81st column.
set wildmenu 							" Set wildmenu to show options when using tab autocomplete.
set backspace=2 						" Have backspace behave as it does in other applications.
set nrformats+=alpha nrformats-=octal	" Enable inc/dec for alphabetical characters, disable for octal.
set clipboard=unnamedplus               " Integrate with the system clipboard.
set scrolloff=15 						" Keep at least 15 lines up and down from the cursor if possible.
set mouse=

" Folding config
set fillchars=fold:\ ,vert:\ ,
set foldmethod=indent
set foldminlines=0
set nofoldenable

" VIM scrolling becomes very slow when having to syntax highlight long lines.
set wrap!
set synmaxcol=200

source /home/master/Workspace/github.com/vmitov/dotfiles/vim/plugins.vim

colorscheme onedark

" Remove trailing spaces.
autocmd BufWritePre * :silent! %s/\s\+$//

""""""""""""
" Mappings "
""""""""""""
let mapleader = ";" " Change leader key.
map <leader>p :CtrlPMixed<cr>
map <leader>n :bn<cr>
map <leader>d :bd<cr>
nnoremap <esc><esc> :silent! nohls<cr>

noremap <leader>s :update<CR>

" Use ctrl + hjkl to navigate in splits
nnoremap <C-H> <C-W>h|xnoremap <C-H> <C-W>h|
nnoremap <C-N> <C-W>j|xnoremap <C-N> <C-W>j|
nnoremap <C-E> <C-W>k|xnoremap <C-E> <C-W>k|
nnoremap <C-I> <C-W>l|xnoremap <C-I> <C-W>l|

" Use ctrl + alt + hjkl to resize windows
nnoremap <C-M-h> :vertical resize -2<CR>
nnoremap <C-M-n> :resize -2<CR>
nnoremap <C-M-e> :resize +2<CR>
nnoremap <C-M-i> :vertical resize +2<CR>

"""""""""
" Other "
"""""""""

" Run last to reload vim-colemak to remap any overridden keys.
source $HOME/.vim/plugged/vim-colemak/plugin/colemak.vim
