DEFAULT_USER='master'
POWERLEVEL9K_MODE='awesome-patched'

## Segments
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
	date time command_execution_time background_jobs status
	newline newline
	context dir vcs
)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode)

## Result segments confg
POWERLEVEL9K_DATE_FORMAT="%D{%d %b}"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_DATE_BACKGROUND='236'
POWERLEVEL9K_TIME_BACKGROUND='236'

## Context segment config
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_DIR_SHOW_WRITABLE=true

## Mode segments config
POWERLEVEL9K_VI_INSERT_MODE_STRING=""
POWERLEVEL9K_VI_COMMAND_MODE_STRING="N"
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='palegreen1'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='236'
