##############
# ZSH Config #
##############
export TERM="screen-256color"
export ZSH="/home/master/.oh-my-zsh"

ZSH_THEME="powerlevel9k/powerlevel9k"
HYPHEN_INSENSITIVE="true"

plugins=(
  colemak
  git
  go
  kubectl
  minikube
  terraform
  vi-mode
  z
)

source $ZSH/oh-my-zsh.sh
source ~/src/github.com/vmitov/dotfiles/zsh/theme.zsh
source ~/src/github.com/vmitov/dotfiles/zsh/vi-mode.zsh
source ~/src/github.com/vmitov/dotfiles/zsh/key-bindings.zsh
source ~/.local.zsh

unsetopt share_history
autoload -U +X bashcompinit && bashcompinit
export LANG=en_US.UTF-8
export EDITOR=vim

# z
. ~/.oh-my-zsh/plugins/z/z.sh

# Usefull aliases

alias suvim='sudo -E vim'
