# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

##############
# ZSH Config #
##############
export ZSH="/home/master/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"
HYPHEN_INSENSITIVE="true"

plugins=(
  colemak
  git
  golang
  kubectl
  minikube
  terraform
  z
)

source $ZSH/oh-my-zsh.sh
source ~/.local.zsh

unsetopt share_history
autoload -U +X bashcompinit && bashcompinit
export LANG=en_US.UTF-8
export EDITOR=vim

# z
. ~/.oh-my-zsh/plugins/z/z.sh

# Useful aliases

alias vim='nvim'
alias suvim='sudo -E vim'

[[ ! -f ~/Workspace/github.com/vmitov/dotfiles/zsh/p10k.zsh ]] || source ~/Workspace/github.com/vmitov/dotfiles/zsh/p10k.zsh
